# Site settings
title: Ty G. Lewis
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://tyglewis.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments

redcarpet:
   extensions: [no_fenced_code_blocks]
